apiVersion: v1
kind: Service

metadata:
  name: kubernete-demo-api-service
  labels:
    app: kubernete-demo-api

spec:
  selector:
    app: kubernete-demo-api

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: NodePort